Feature/mobile view
consensusnetworks/casimir pull request #383
Opened 2023-07-31 19:35 UTC by DemogorGod

Hey guys upon @natemiller1 request I have created a mobile view that encapsulates everything in the app that we have created, I know that we are adding other things in the app and i am willing to change this as we add more views and concepts into the app as well. Thanks! Enjoy!

Some kinks to workout with @ccali11  figuring out the user flow as on connects a wallet to sign in (which tab to follow to and how it connects) other kinks to work out as the flow gets ironed out. 

https://github.com/consensusnetworks/casimir/assets/63758598/5f4c0846-9a77-4b95-beff-4d5264ab35df

2023-07-31 19:40 UTC, DemogorGod commented
@ccali11 @shanejearley 

there is a conflic in `contracts/ethereum/docs/index.md` I will let that be handled by you guys so i do not mess it up, Thanks!

2023-08-01 13:20 UTC, ccali11 requested changes
@DemogorGod - Awesome work. App looks great. I prefer icon/navigation tray to be on the bottom of the screen, but I imagine you tried that first. Might be worth revisiting and figuring it out (in a later PR) unless you have good examples of other familiar apps with good UX that use that design approach. 

I made a couple small comments with tiny tweaks/suggestions. Take a look and let me know and then I will approve.

2023-08-01 13:20 UTC, ccali11 commented on apps/web/src/App.vue
> +    window.addEventListener('orientationchange', findScreenDimenstions)
camelCase `orientationChange`?

2023-08-01 13:20 UTC, ccali11 commented on apps/web/src/App.vue
> +  import MobileLayout from '@/layouts/mobile-layout.vue'
Ok cool. So you went with the mobile layout approach. 👍

2023-08-01 13:20 UTC, ccali11 commented on apps/web/src/components/mobileComponents/MobileBreakdown.vue
> +    // TODO: Potentially find a better place to initialize these listeners
We can resolve this in a separate PR

2023-08-01 13:20 UTC, ccali11 commented on apps/web/src/components/mobileComponents/MobileConnectWallets.vue
> +const convertString = (inputString: string) => {
Rename to something like `abbreviateAddress`. This is also probably used several places throughout the app; should we have a `useHelpers` composable or something like that?

2023-08-01 13:20 UTC, ccali11 commented on apps/web/src/layouts/mobile-layout.vue
> +  setTimeout(() =>{
why `setTimeout`?

2023-08-01 13:20 UTC, ccali11 commented on apps/web/src/components/mobileComponents/MobileBreakdown.vue
> +
Remove space

2023-08-01 13:20 UTC, ccali11 commented on apps/web/src/layouts/mobile-layout.vue
> +
Remove space

2023-08-01 13:27 UTC, ccali11 commented
And @shanejearley - I pulled down to see what the changes were to the file with conflicts; I'm not sure which process is managing the `contracts/ethereum/docs/index.md`, but I suppose there are what looks like some benign changes. Will let you address.

2023-08-01 16:24 UTC, shanejearley commented
TS errors need fixing.

2023-08-01 18:35 UTC, shanejearley commented on apps/web/src/layouts/mobile-layout.vue
> +
Resolved.

2023-08-01 18:38 UTC, shanejearley commented
@DemogorGod make sure to pull and install before making new commits to respond to Chris's requests. Conflicts and TS errors are resolved.

2023-08-02 03:02 UTC, DemogorGod commented
upon request from the ui designer, this branch will be deleted and we will move away from the mobile layout.

2023-08-02 03:02 UTC, closed without merging